# Using expressions that can fail

일이 잘 진행되고 있지만, 아직 작은 문제가 하나 더 있습니다.
실패할 수 있는 표현식을 사용하고 싶다면 어떻게 해야 할까요?

아래 코드를 봐봅시다.

```swift
import Foundation

func ifelse<V>(_ condition: Bool,
               _ valueTrue: @autoclosure () -> V,
               _ valueFalse: @autoclosure () -> V) -> V {
    condition ? valueTrue() : valueFalse()
}

func expensiveFailingValue1() throws -> Int {
  print("side-effect-1")
  return 2
}

func expensiveFailingValue2() throws -> Int {
  print("side-effect-2")
  return 1729
}

let taxicab = ifelse(.random(),
                     try expensiveFailingValue1(),
                     try expensiveFailingValue2())
```

이것은 `autoclosure`가 예외를 던지는 클로저를 예상하지 않기 때문에 컴파일에 실패합니다.
컴파일러로부터의 특별한 도움 없이, 다음과 같은 다른 함수 버전을 만들어 해결하려고 할 수도 있습니다.

```swift
func ifelseThrows<V>(_ condition: Bool,
                     _ valueTrue: @autoclosure () throws -> V,
                     _ valueFalse: @autoclosure () throws -> V) throws -> V {
    condition ? try valueTrue() : try valueFalse()
}

func expensiveFailingValue1() throws -> Int {
  print("side-effect-1")
  return 2
}

func expensiveFailingValue2() throws -> Int {
  print("side-effect-2")
  return 1729
}

let taxicab2 = try ifelseThrows(.random(),
                            try expensiveFailingValue1(),
                            try expensiveFailingValue2())

```

이 코드는 작동하지만, 보기에 좋지 않습니다.
다행히도, 더 나은 방법이 있습니다.
다양한 경우를 처리할 수 있는 함수의 한 버전을 작성할 수 있습니다.

```swift
func ifelse<V>(_ condition: Bool,
                     _ valueTrue: @autoclosure () throws -> V,
                     _ valueFalse: @autoclosure () throws -> V) rethrows -> V {
    condition ? try valueTrue() : try valueFalse()
}
```

핵심은 `rethrows`를 사용하는 것입니다.
`Rethrows`는 실패한 클로저의 오류를 호출자에게 전파합니다.
클로저 매개변수 중 어느 것도 예외를 던지지 않으면, 함수는 비-예외 함수로 간주되어 `'try'`로 표시할 필요가 없습니다.

이 단일 버전을 사용하면, 다음과 같은 모든 변형이 작동합니다.

```swift
func ifelse<V>(_ condition: Bool,
                     _ valueTrue: @autoclosure () throws -> V,
                     _ valueFalse: @autoclosure () throws -> V) rethrows -> V {
    condition ? try valueTrue() : try valueFalse()
}

func expensiveValue1() -> Int {
  print("side-effect-1")
  return 2
}

func expensiveValue2() -> Int {
  print("side-effect-2")
  return 1729
}

func expensiveFailingValue1() throws -> Int {
  print("side-effect-1")
  return 2
}

func expensiveFailingValue2() throws -> Int {
  print("side-effect-2")
  return 1729
}

let value = ifelse(.random(), 100, 0 )
let taxicab = ifelse(.random(),
                     expensiveValue1(),
                     expensiveValue2())
let taxicab2 = try ifelse(.random(),
                          try expensiveFailingValue1(),
                          try expensiveFailingValue2())
let taxicab3 = try ifelse(.random(),
                           expensiveValue1(),
                           try expensiveFailingValue2())
let taxicab4 = try ifelse(.random(),
                          try expensiveFailingValue1(),
                          expensiveValue2())
```

`ifelse` 를 완성하는 데 가까워지고 있습니다.
추가적인 추상화 계층의 비용을 지불하고 싶지 않고,
구현이 결코 변경되지 않을 것이므로, 함수를 `'@inlinable'`로 표시하는 것이 합리적입니다.
이 추가된 키워드는 메서드의 본문이 함수 호출의 오버헤드 없이 클라이언트 코드에 직접 포함되어야 함을 컴파일러에게 암시합니다.

```swift
@inlinable
func ifelse<V>(_ condition: Bool,
                     _ valueTrue: @autoclosure () throws -> V,
                     _ valueFalse: @autoclosure () throws -> V) rethrows -> V {
    condition ? try valueTrue() : try valueFalse()
}
```

> 📝 Note.
> 
> `'@inlinable'` 보다 강력한 형태의 속성이 사적으로 사용 가능합니다.
> Swift 소스를 탐색하면 이러한 속성을 볼 수 있습니다.
> 그 중 하나는 `'@_transparent'`로, 항상 기본 구현을 "투과"하여 볼 수 있습니다.
> 이는 `'-Onone'`에서도 인라인 처리를 하며, 디버깅 시 스택 프레임을 포함하지 않습니다.
> 여기에서 자세한 내용을 확인하세요: https://github.com/apple/swift/blob/main/docs/TransparentAttr.md
